services:

  postgres:
    image: postgres:latest
#    container_name: jakkarin-postgres
    environment:
      POSTGRES_DB: ssotest
      POSTGRES_USER: ssodev
      POSTGRES_PASSWORD: sso2022ok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssodev -d ssotest"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: